[package]
name = "heim-winservice"
version = "0.0.1"
authors = ["svartalf <self@svartalf.info>"]
edition = "2018"
description = "Placeholder crate"
repository = "https://github.com/heim-rs/heim"
readme = "README.md"
license = "Apache-2.0 OR MIT"

[badges]
maintenance = { status = "experimental" }
